package edu.uci.eecs.crowdsafe.common.data.graph;

public enum MetaNodeType {
	NORMAL(true),
	CONTEXT_ENTRY,
	CONTEXT_EXIT,
	TRAMPOLINE(true),
	RETURN(true),
	SIGNAL_HANDLER(true),
	SIGRETURN(true),
	BLACK_BOX_SINGLETON,
	CLUSTER_ENTRY, // not generated by the VM
	CLUSTER_EXIT; // not generated by the VM

	public final boolean isExecutable;

	private MetaNodeType() {
		this(false);
	}

	private MetaNodeType(boolean isExecutable) {
		this.isExecutable = isExecutable;
	}
}
