sbs_diasymreader.dll
sbs_iehost.dll
sbs_microsoft.jscript.dll
sbs_microsoft.vsa.vb.codedomprocessor.dll
sbs_mscordbi.dll
sbs_mscorrc.dll
sbs_mscorsec.dll
sbs_system.configuration.install.dll
sbs_system.data.dll
sbs_system.enterpriseservices.dll
sbs_systementerpriseservices.dll
sbs_vsavb7rt.dll
sbs_wminet_utils.dll
