#!/bin/bash

function append_jars() {
  jar_dir=$1

  for j in `find $jar_dir -name '*.jar'`; do 
    cp=$cp:$j
  done
}

function append_classpath() {
  project=$1
  
  if [ -z $$project ]; then
    echo "Environment variable $project is required."
    exit
  fi
  
  project_path=${!project}
  
  if [ ! -e $project_path ]; then
    echo "The path of $project could not be found: $project_path"
    exit
  fi
  
  #echo "Appending classpath for $project: "$project_path

  if [ -z $cs_jar_dir ]
  then
    cp=$cp:$project_path/bin
  fi
  
  if [ -e $project_path/lib ]
  then
    append_jars $project_path/lib
  fi
}

function check_help() {
  if [ $1 == "--help" ]
  then
    $2
    exit
  fi
}

function decode_project_dirs() {
  project_codes=$1
  project_dirs=""

  IFS=','
  for p in $project_codes
  do
    project_dir="cs"$p
    project_dir=${!project_dir}
    project_dir=${project_dir%/}
    project_dirs=$project_dirs" "$project_dir
  done
  IFS=' '
}

if [ ! -z $CROWD_SAFE_JAR_DIR ]
then
  cs_jar_dir=$CROWD_SAFE_JAR_DIR
  append_jars $cs_jar_dir
fi

