#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "cs-pack -s <record-size> <dat-file> [ <dat-file> ... ]"
}

check_help $1 print_usage

append_classpath "CROWD_SAFE_COMMON_DIR"

main_class="edu.uci.eecs.crowdsafe.common.data.graph.execution.packer.ProcessExecutionGraphPacker"

java -cp $cp $main_class $@

