#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "print-graph -o <output-file> { c: | e: }<run-dir>"
}

check_help $1 usage

append_classpath "CROWD_SAFE_COMMON_DIR"

main_class="edu.uci.eecs.crowdsafe.common.main.GraphSummaryPrinter"

#echo "java -cp $cp $main_class $@"
java -cp $cp $main_class $@

