#!/bin/bash

. $csc/scripts/cs-common

function usage() {
  echo "transform-graphs [ -l <log-file> ]"
  echo "\t-o <output-base-dir> <run-dir> [ <run-dir> ... ]"
}

check_help $1 usage

while getopts "l:o:" option
do
  case $option in
    o ) output_basedir=$OPTARG;;
    l ) log_file=$OPTARG;;
    * ) usage; exit;;
  esac
done
shift $((OPTIND-1))

local_dir=$(pwd)

for f in $@
do
  if [ ! -z $output_basedir ] 
  then
    output_dir=$output_basedir/${f/$local_dir}
    mkdir -p $output_dir
    
    if [ -z "$log_file" ] 
    then
      log_option="-l "${output_dir%/}"/transform-graphs.log"
    else
      log_option="-l "$log_file
    fi

    rm -f $output_dir/*
    output_option="-o "$output_dir
    input="-i "$f
  else
    input=$f
  fi

  transform-graph $log_option $input $output_option
done

